<?php
$name = "name";
$thankU = "Thank you";
$tAndC = "Terms & Conditions";
// btn
$btnNext = "Next";
$btnBack = "Back";
$btnPreview = "Preview";

$ind01 = "2020 School Information Day";
$ind02 = "2th December 2020";
$ind03 = "Our School Information Day will be held on 12th December 2020 (Saturday). We will conduct two briefing sessions about our school for senior primary students and their parents. Each briefing session will include a general introduction of the school, our curriculum, activities for students as well as admission criteria. Visitors are also welcomed to tour the school during school opening hours.";
$ind04 = "Briefing Sessions";
$ind05 = "1st Session: 2:00 p.m. – 3:15 p.m.";
$ind06 = "2nd Session: 4:00 p.m. – 5:15 p.m.";
$ind07 = "(Contents of the two sessions are identical.)";
$ind08 = "For details, please contact us at 2336 3034.";
// form.php
$form01 = "School Information Day 2020 Registration";
$form02 = "Please enter the following information for registratio";
$form03 = "NAME OF STUDENT";
$form04 = "Chinese or English characters only)";
$form05 = "NAME OF PARENT";
$form06 = "EMAIL OF PARENT";
$form07 = "CONFIRM EMAIL OF PARENT";
$form08 = "SESSION ATTENDING";
$form09 = "NO. OF SEATS RESERVED";
$form10 = "PRIMARY SCHOOL ATTENDING";
$form11 = "Neighbours";
$form12 = "Other";
$form13 = "CONTACT NUMBER";
$textPlease2 ="Please ensure the information above is correct before submission. Duplicate registration will not be accepted. A confirmation message will be sent to you via SMS after the completion of registration. Please show the confirmation upon entry to the School Hall. Thank you.";


$thkInfo = ""
?>
